openapi: 3.0.0
info:
  title: Sample API
  description: User API
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Production
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'schemas/userResponse.yml'
    post:
      summary: Creates a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/user.yml'
      responses:
        '201':
          description: Created
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - in: path
          name: userId
          required: true
          schema: {
            type: integer,
            format: int32
          }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'schemas/userResponse.yml'
    patch:
      summary: patch user by ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/user.yml'
      parameters:
        - in: path
          name: userId
          required: true
          schema: {
            type: integer,
            format: int32
          }
      responses:
        '200':
          description: Ok