openapi: 3.0.0
info:
  title: Sample API
  description: User API
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Production
paths:
  /events:
    get:
      summary: Returns a list of events.
      description: List of events.
      operationId: 'getEvents'
      responses:
        '200':    # status code
          description: A JSON array of events
          content:
            application/json:
              schema:
                $ref: 'schemas/eventsResponse.yml'
